### ISSUE TITLE
Crash after update to TYPO3 11.5.33 on php7.4

### ISSUE THREAD

**Issue by Padina14** [TYPO3-CMS/styleguide#477]
I have had a running system. After Update to TYPO3 11.5.33 the system crashed. The local ddev was running on PHP 7.4.
 I used the following line in the composer-definition.
 "
  "require-dev": {
        "phpunit/phpunit": "~9.5",
        "typo3/cms-styleguide": "*",
  ..."
  
![Bildschirmfoto 2023-12-15 um 10 47 48](https://github.com/TYPO3-CMS/styleguide/assets/63228213/dae4604c-4b9e-495c-9df6-3b8854704353)

**Comment by lolli42** [comment]
styleguide needs a version constraint that fits the core version:
`composer require --dev typo3/cms-styleguide:^11`
^12 and main don't work with core v11.

**Comment by Padina14** [comment]
Your composer-definition should prevent my mistake. 
Use the require-definition in  your composer.json to define the used TYPO3-Version and PHP-Version:
```

 "require": {
        "php" : "^8.1.0 || ^8.2.0",
        "typo3/cms-core": "^12.4",
...
```

**Comment by sbuerk** [comment]
Please check the requirements of software you use. TYPO3 v12 has a minimum requirement of PHP 8.1, but you running ddev with PHP7.4 ... that is to low. 

Please use a suitable php version before running the composer require command with the higher pgp version. 

Maybe you use config atform and therefore disa led a propper version check.

**Comment by Padina14** [comment]
You missunderstand me. I know, that my php-version is not compatible with the current version 12.
The porpose of my issue:
I wish that this extension define itself the requirements in its own composer.json. 
If you do that, then the composer would have not used this current version, which failed in my extension (screenshot).
I hoped with this issue that you would make your composer better and more restrict.

**Comment by lolli42** [comment]
Hey. Your proposal is good and we'd of course do that: This is solved with v13 version of ext:styleguide (which is integrated into core monorepo). With earlier versions, this gave nasty cross-dependencies between core and styleguide, so we couldn't do that. See https://github.com/TYPO3-CMS/styleguide/issues/236 for a similar answer by me to the same question.

**Comment by lolli42** [comment]
Doing this in v13 monorepo now: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82274
